'use client';
import {useEffect,useState} from 'react';
import {Menu,X} from 'lucide-react';
import {Dialog,DialogTrigger,DialogContent,DialogTitle,DialogClose} from '@/components/ui/dialog';
import {Slider} from '@/components/ui/slider';
import {validSettings} from './local-store';
import type {Settings} from './local-store';
export default function Appearance({value,onSave,ready}:{value:Settings;onSave:(s:Settings)=>Promise<boolean>;ready:boolean}){const[open,setOpen]=useState(false),[draft,setDraft]=useState(value),[saving,setSaving]=useState(false),[error,setError]=useState('');useEffect(()=>{const active=open?draft:value;document.documentElement.style.setProperty('--settings-offset',(active.settingsOffset??7)+'px');document.documentElement.style.setProperty('--settings-gap',(active.settingsGap??4)+'px')},[open,draft,value]);return <Dialog modal={false} open={open} onOpenChange={v=>{setOpen(v);setDraft(value);setError('')}}><DialogTrigger className="settings-trigger" disabled={!ready}><Menu size={20}/><img className="settings-label" src="./settings-label.png" alt="設定" width="189" height="85"/></DialogTrigger><DialogContent className="appearance-dialog position-adjust-dialog" showCloseButton={false}><div className="composer-head"><DialogTitle>設定</DialogTitle><DialogClose className="icon-button" aria-label="設定を閉じる"><X size={20}/></DialogClose></div><div className="color-fields"><label>背景色<input type="color" value={draft.background} onChange={e=>setDraft({...draft,background:e.target.value})}/></label><label>ボタンの色<input type="color" value={draft.accent} onChange={e=>setDraft({...draft,accent:e.target.value})}/></label></div><div className="position-sliders"><label id="offset-label">上下の位置 <output>{draft.settingsOffset??7}px</output></label><Slider aria-labelledby="offset-label" min={-20} max={30} step={1} value={[draft.settingsOffset??7]} onValueChange={v=>setDraft({...draft,settingsOffset:Array.isArray(v)?v[0]:v})}/><label id="gap-label">ボタンと文字の間隔 <output>{draft.settingsGap??4}px</output></label><Slider aria-labelledby="gap-label" min={0} max={24} step={1} value={[draft.settingsGap??4]} onValueChange={v=>setDraft({...draft,settingsGap:Array.isArray(v)?v[0]:v})}/></div>{error&&<p role="alert" className="error">{error}</p>}<button className="primary" disabled={saving||!validSettings(draft)} onClick={async()=>{setSaving(true);if(await onSave(draft))setOpen(false);else setError('設定を保存できませんでした。');setSaving(false)}}>保存</button></DialogContent></Dialog>}



