'use client';
import {useEffect,useRef,useState} from 'react';
import InkPad from './ink-pad';
import SortableTasks from './sortable-tasks';
import {reorderTasks} from './reorder';
import {cleanTasks,completion,COMPLETED_TTL} from './task-lifecycle';
import {readData,writeData,defaults,contrast} from './local-store';
import type {Settings} from './local-store';
import {useTaskTools} from './task-tools';
const FIXED_BACKGROUND='#fffdf0';
type Point={x:number;y:number};type Stroke=Point[];type Tool='pen'|'eraser';
type Task={id:string;title?:string;strokes?:Stroke[];checkStrokes?:Stroke[];boxVariant?:number;done:boolean;completedAt?:number};
function variant(task:Task){if(task.boxVariant&&task.boxVariant>=1&&task.boxVariant<=3)return task.boxVariant;let n=0;for(const c of task.id)n=(n*31+c.charCodeAt(0))>>>0;return n%3+1}
function InlineTask({task,tool,onSave}:{task:Task;tool:Tool;onSave:(task:Task)=>Promise<boolean>}){
const[ink,setInk]=useState<Stroke[]>(task.strokes??[]),[check,setCheck]=useState<Stroke[]>(task.checkStrokes??[]);const inkRef=useRef(ink),checkRef=useRef(check);inkRef.current=ink;checkRef.current=check;
useEffect(()=>{setInk(task.strokes??[]);setCheck(task.checkStrokes??[])},[task.strokes,task.checkStrokes]);
function changeInk(next:Stroke[]){inkRef.current=next;setInk(next)}function changeCheck(next:Stroke[]){checkRef.current=next;setCheck(next)}
async function saveInk(){if(task.strokes)await onSave({...task,strokes:inkRef.current})}
async function saveCheck(){const nextDone=checkRef.current.some(s=>s.length>1);await onSave({...completion({...task,checkStrokes:checkRef.current},nextDone),boxVariant:variant(task)})}
return <article className={`task-card ${task.done?'completed':''}`} data-sort-id={task.id} data-sort-group={task.done?'done':'active'}>
<button className="sort-handle" data-sort-handle aria-label="長押しして並べ替え"><img src="./task-handle.png" alt=""/></button>
<div className="hand-check"><img src={`./task-box-${variant(task)}.png`} alt=""/><InkPad className="check-pad" width={100} height={100} strokeWidth={4} eraseRadius={32} strokes={check} onChange={changeCheck} onStart={()=>{}} onEnd={saveCheck} tool={tool}/></div>
<div className="task-title">{task.strokes?<InkPad className="inline-task-pad" strokes={ink} onChange={changeInk} onStart={()=>{}} onEnd={saveInk} tool={tool}/>:<h3>{task.title}</h3>}</div>
</article>}
export default function Home(){
const[tasks,setTasks]=useState<Task[]>([]),[ready,setReady]=useState(false),[error,setError]=useState(''),[editing,setEditing]=useState<string|null>(null),[strokes,setStrokes]=useState<Stroke[]>([]),[text,setText]=useState(''),[mode,setMode]=useState<'ink'|'text'>('ink'),[tool,setTool]=useState<Tool>('pen');const[settings,setSettings]=useState<Settings>(defaults);const busy=useRef(false);
useEffect(()=>{readData().then(data=>{setTasks(data.tasks);setSettings(data.settings);setReady(true)}).catch(()=>setError('保存領域を開けませんでした。Safariの通常モードで開いてください。'))},[]);
useEffect(()=>{document.documentElement.style.setProperty('--page-bg',FIXED_BACKGROUND);document.documentElement.style.setProperty('--page-ink',contrast(FIXED_BACKGROUND));document.documentElement.style.setProperty('--user-accent',settings.accent);document.documentElement.style.setProperty('--accent-ink',contrast(settings.accent));document.title='doodle do';document.querySelector('meta[name="theme-color"]')?.setAttribute('content',FIXED_BACKGROUND)},[settings]);
async function persist(next:Task[],appearance:Settings=settings){if(busy.current)return false;busy.current=true;try{const saved=await writeData({tasks:next,settings:appearance});setTasks(saved.tasks);setEditing(id=>id&&id!=='new'&&!saved.tasks.some(t=>t.id===id)?null:id);setSettings(appearance);setError('');return true}catch{setError('保存できませんでした。端末の空き容量を確認してください。');return false}finally{busy.current=false}}
useEffect(()=>{if(!ready)return;let timer:ReturnType<typeof setTimeout>;function schedule(){const deadlines=tasks.filter(t=>t.done&&t.completedAt!==undefined).map(t=>t.completedAt!+COMPLETED_TTL);if(!deadlines.length)return;timer=setTimeout(check,Math.min(Math.max(0,Math.min(...deadlines)-Date.now()),2147483647))}async function check(){clearTimeout(timer);if(busy.current){timer=setTimeout(check,500);return}const next=cleanTasks(tasks);if(next.length!==tasks.length){if(!await persist(next))timer=setTimeout(check,30000)}else schedule()}function visible(){if(document.visibilityState==='visible')void check()}schedule();window.addEventListener('focus',check);document.addEventListener('visibilitychange',visible);return()=>{clearTimeout(timer);window.removeEventListener('focus',check);document.removeEventListener('visibilitychange',visible)}},[ready,tasks,settings]);
async function removeTask(){if(editing&&editing!=='new')await persist(tasks.filter(t=>t.id!==editing))}
function open(task?:Task){setTool('pen');setEditing(task?.id??'new');setStrokes(task?.strokes??[]);setText(task?.title??'');setMode(task?.title?'text':'ink')}
async function save(){if(mode==='ink'?!strokes.length:!text.trim())return;const old=tasks.find(t=>t.id===editing);const task:Task={id:editing==='new'?crypto.randomUUID():editing!,done:old?.done??false,completedAt:old?.completedAt,checkStrokes:old?.checkStrokes,boxVariant:old?.boxVariant??Math.floor(Math.random()*3)+1,...(mode==='ink'?{strokes}:{title:text.trim()})};if(await persist(editing==='new'?[...tasks,task]:tasks.map(t=>t.id===editing?task:t)))setEditing(null)}
async function updateTask(next:Task){return persist(tasks.map(t=>t.id===next.id?next:t))}
useTaskTools(tasks,async(id,done)=>{if(!ready||!tasks.some(t=>t.id===id))return false;return persist(tasks.map(t=>t.id===id?completion(t,done):t))});const active=tasks.filter(t=>!t.done),done=tasks.filter(t=>t.done);
return <main className="workspace"><header className="masthead"><div className="brand"><img className="header-app-icon" src="./app-icon.png" alt="" width="46" height="46"/><img className="brand-logo" src="./doodle-do-logo.png" alt="doodle do" width="265" height="66"/></div></header>{error&&<p className="error" role="alert">{error}</p>}
{editing!==null&&<section className="composer" aria-label="タスクを編集"><div className="composer-head"><button className="icon-button composer-close" aria-label="編集を閉じる" onClick={()=>setEditing(null)}><span className="close-mark" aria-hidden="true">&#x2716;&#xFE0E;</span></button></div><div className="mode-row"><button aria-label="手書き" aria-pressed={mode==='ink'} onClick={()=>setMode('ink')}>✍️</button><button aria-label="文字入力" aria-pressed={mode==='text'} onClick={()=>setMode('text')}>⌨️</button></div><div className="editor-tools-row">{mode==='ink'&&<div className="ink-tools"><button className="subtle" aria-label="ペン" aria-pressed={tool==='pen'} onClick={()=>setTool('pen')}>✏️</button><button className="subtle" aria-label="消しゴム" aria-pressed={tool==='eraser'} onClick={()=>setTool('eraser')}>🫥</button></div>}{editing!=='new'&&<button className="delete-task" aria-label="タスクを削除" onClick={removeTask}>🗑️</button>}</div>{mode==='ink'?<InkPad strokes={strokes} onChange={setStrokes} onStart={()=>{}} tool={tool}/>:<label className="text-label"><input aria-label="タスクの文字入力" autoFocus value={text} maxLength={100} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.nativeEvent.isComposing)save()}}/></label>}<div className="composer-footer emoji-footer"><button className="primary" aria-label={editing==='new'?'追加する':'保存する'} onClick={save} disabled={mode==='ink'?!strokes.length:!text.trim()}>✔️</button></div></section>}
<div className="board single-board"><section className="column task-column"><div className="column-heading"><h2><span className="status-dot"/><img className="in-progress-label" src="./in-progress-label.png" alt="作業中" width="218" height="85"/></h2><div className="inline-ink-tools"><button aria-label="ペン" aria-pressed={tool==='pen'} onClick={()=>setTool('pen')}>✏️</button><button aria-label="消しゴム" aria-pressed={tool==='eraser'} onClick={()=>setTool('eraser')}>🫥</button></div></div><SortableTasks onMove={async(from,to,place)=>persist(reorderTasks(tasks,from,to,place))} onDelete={async id=>persist(tasks.filter(t=>t.id!==id))}>{active.map(task=><InlineTask key={task.id} task={task} tool={tool} onSave={updateTask}/>)}<button className="add-card" disabled={!ready} onClick={()=>open()}><img className="add-task-label" src="./add-task-label.png" alt="タスクを追加" width="524" height="85"/></button><div className="delete-drop-zone" data-delete-zone><img src="./delete-task-label.png" alt="タスクを削除"/></div>{done.map(task=><InlineTask key={task.id} task={task} tool={tool} onSave={updateTask}/>)}</SortableTasks></section></div></main>}
