'use client';
import {useEffect,useRef,useState} from 'react';
import type {ReactNode} from 'react';
type Place='before'|'after';
export default function SortableTasks({children,onMove,onDelete}:{children:ReactNode;onMove:(from:string,to:string,place:Place)=>Promise<boolean>;onDelete:(id:string)=>Promise<boolean>}){
const root=useRef<HTMLDivElement>(null),callback=useRef(onMove),deleteCallback=useRef(onDelete);callback.current=onMove;deleteCallback.current=onDelete;const[message,setMessage]=useState('');
useEffect(()=>{const el=root.current!;let timer:ReturnType<typeof setTimeout>|undefined;let source:HTMLElement|null=null,target:HTMLElement|null=null,place:Place='before';let deleteTarget=false,dragging=false,x=0,y=0,pointer:number|null=null,touch:number|null=null;
function clearTarget(){target?.classList.remove('drop-before','drop-after')}
function reset(){clearTimeout(timer);source?.classList.remove('dragging-task');clearTarget();el.querySelector('[data-delete-zone]')?.classList.remove('delete-target');source=null;target=null;deleteTarget=false;dragging=false;pointer=null;touch=null;el.classList.remove('sorting-tasks')}
function begin(node:EventTarget|null,px:number,py:number){const element=node instanceof Element?node:null;if(!element?.closest('[data-sort-handle]'))return false;const card=element.closest<HTMLElement>('[data-sort-id]');if(!card||!el.contains(card))return false;source=card;x=px;y=py;timer=setTimeout(()=>{if(!source)return;dragging=true;source.classList.add('dragging-task');el.classList.add('sorting-tasks');setMessage('上下に動かして、指を離すと並べ替えます。')},150);return true}
function move(px:number,py:number){if(!source)return;if(!dragging){if(Math.hypot(px-x,py-y)>10)reset();return}const zone=el.querySelector<HTMLElement>('[data-delete-zone]'),zr=zone?.getBoundingClientRect();deleteTarget=!!zr&&px>=zr.left&&px<=zr.right&&py>=zr.top&&py<=zr.bottom;zone?.classList.toggle('delete-target',deleteTarget);clearTarget();if(deleteTarget){target=null;return}const group=source.dataset.sortGroup;const cards=Array.from(el.querySelectorAll<HTMLElement>('[data-sort-id]')).filter(c=>c!==source&&c.dataset.sortGroup===group);let best:HTMLElement|null=null,bestPlace:Place='before',distance=Infinity;for(const c of cards){const r=c.getBoundingClientRect();for(const candidate of [{p:'before' as Place,y:r.top},{p:'after' as Place,y:r.bottom}]){const d=Math.abs(py-candidate.y);if(d<distance){distance=d;best=c;bestPlace=candidate.p}}}target=best;place=bestPlace;if(target)target.classList.add(place==='before'?'drop-before':'drop-after');if(py<70)window.scrollBy(0,-14);else if(py>window.innerHeight-70)window.scrollBy(0,14)}
async function finish(){const from=source?.dataset.sortId,to=target?.dataset.sortId,active=dragging,finalPlace=place,remove=deleteTarget;reset();if(active&&from&&remove){const ok=await deleteCallback.current(from);setMessage(ok?'タスクを削除しました。':'タスクを削除できませんでした。')}else if(active&&from&&to&&from!==to){const ok=await callback.current(from,to,finalPlace);setMessage(ok?'並び順を保存しました。':'並び順を保存できませんでした。')}else setMessage('')}
function touchStart(e:TouchEvent){if(e.touches.length!==1){reset();return}const t=e.changedTouches[0];if(begin(e.target,t.clientX,t.clientY))touch=t.identifier}
function touchMove(e:TouchEvent){const t=Array.from(e.changedTouches).find(t=>t.identifier===touch);if(!t)return;if(dragging&&e.cancelable)e.preventDefault();move(t.clientX,t.clientY)}function touchEnd(e:TouchEvent){if(Array.from(e.changedTouches).some(t=>t.identifier===touch))void finish()}
function down(e:PointerEvent){if(e.pointerType==='touch'||e.button!==0)return;if(begin(e.target,e.clientX,e.clientY))pointer=e.pointerId}function pointerMove(e:PointerEvent){if(e.pointerId===pointer){if(dragging)e.preventDefault();move(e.clientX,e.clientY)}}function up(e:PointerEvent){if(e.pointerId===pointer)void finish()}function cancelPointer(e:PointerEvent){if(e.pointerId===pointer)reset()}function context(e:Event){if(source)e.preventDefault()}
el.addEventListener('touchstart',touchStart,{passive:true});el.addEventListener('touchmove',touchMove,{passive:false});el.addEventListener('touchend',touchEnd);el.addEventListener('touchcancel',reset);el.addEventListener('pointerdown',down);window.addEventListener('pointermove',pointerMove);window.addEventListener('pointerup',up);window.addEventListener('pointercancel',cancelPointer);el.addEventListener('contextmenu',context);
return()=>{reset();el.removeEventListener('touchstart',touchStart);el.removeEventListener('touchmove',touchMove);el.removeEventListener('touchend',touchEnd);el.removeEventListener('touchcancel',reset);el.removeEventListener('pointerdown',down);window.removeEventListener('pointermove',pointerMove);window.removeEventListener('pointerup',up);window.removeEventListener('pointercancel',cancelPointer);el.removeEventListener('contextmenu',context)}},[]);
return <div ref={root} className="cards"><span className="sr-only" role="status">{message}</span>{children}</div>}
